/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DevHarnessRouteImport } from './routes/dev-harness'
import { Route as DevMermaidHarnessRouteImport } from './routes/dev-mermaid-harness'
import { Route as SessionRouteImport } from './routes/session'
import { Route as ApiAgentTurnRouteImport } from './routes/api/agent-turn'
import { Route as ApiIllustrateRouteImport } from './routes/api/illustrate'
import { Route as ApiResearchRouteImport } from './routes/api/research'
import { Route as ApiSkillsRouteImport } from './routes/api/skills'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevHarnessRoute = DevHarnessRouteImport.update({
  id: '/dev-harness',
  path: '/dev-harness',
  getParentRoute: () => rootRouteImport,
} as any)
const DevMermaidHarnessRoute = DevMermaidHarnessRouteImport.update({
  id: '/dev-mermaid-harness',
  path: '/dev-mermaid-harness',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionRoute = SessionRouteImport.update({
  id: '/session',
  path: '/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentTurnRoute = ApiAgentTurnRouteImport.update({
  id: '/api/agent-turn',
  path: '/api/agent-turn',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIllustrateRoute = ApiIllustrateRouteImport.update({
  id: '/api/illustrate',
  path: '/api/illustrate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResearchRoute = ApiResearchRouteImport.update({
  id: '/api/research',
  path: '/api/research',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSkillsRoute = ApiSkillsRouteImport.update({
  id: '/api/skills',
  path: '/api/skills',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dev-harness': typeof DevHarnessRoute
  '/dev-mermaid-harness': typeof DevMermaidHarnessRoute
  '/session': typeof SessionRoute
  '/api/agent-turn': typeof ApiAgentTurnRoute
  '/api/illustrate': typeof ApiIllustrateRoute
  '/api/research': typeof ApiResearchRoute
  '/api/skills': typeof ApiSkillsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dev-harness': typeof DevHarnessRoute
  '/dev-mermaid-harness': typeof DevMermaidHarnessRoute
  '/session': typeof SessionRoute
  '/api/agent-turn': typeof ApiAgentTurnRoute
  '/api/illustrate': typeof ApiIllustrateRoute
  '/api/research': typeof ApiResearchRoute
  '/api/skills': typeof ApiSkillsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dev-harness': typeof DevHarnessRoute
  '/dev-mermaid-harness': typeof DevMermaidHarnessRoute
  '/session': typeof SessionRoute
  '/api/agent-turn': typeof ApiAgentTurnRoute
  '/api/illustrate': typeof ApiIllustrateRoute
  '/api/research': typeof ApiResearchRoute
  '/api/skills': typeof ApiSkillsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dev-harness'
    | '/dev-mermaid-harness'
    | '/session'
    | '/api/agent-turn'
    | '/api/illustrate'
    | '/api/research'
    | '/api/skills'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dev-harness'
    | '/dev-mermaid-harness'
    | '/session'
    | '/api/agent-turn'
    | '/api/illustrate'
    | '/api/research'
    | '/api/skills'
  id:
    | '__root__'
    | '/'
    | '/dev-harness'
    | '/dev-mermaid-harness'
    | '/session'
    | '/api/agent-turn'
    | '/api/illustrate'
    | '/api/research'
    | '/api/skills'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DevHarnessRoute: typeof DevHarnessRoute
  DevMermaidHarnessRoute: typeof DevMermaidHarnessRoute
  SessionRoute: typeof SessionRoute
  ApiAgentTurnRoute: typeof ApiAgentTurnRoute
  ApiIllustrateRoute: typeof ApiIllustrateRoute
  ApiResearchRoute: typeof ApiResearchRoute
  ApiSkillsRoute: typeof ApiSkillsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev-harness': {
      id: '/dev-harness'
      path: '/dev-harness'
      fullPath: '/dev-harness'
      preLoaderRoute: typeof DevHarnessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev-mermaid-harness': {
      id: '/dev-mermaid-harness'
      path: '/dev-mermaid-harness'
      fullPath: '/dev-mermaid-harness'
      preLoaderRoute: typeof DevMermaidHarnessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session': {
      id: '/session'
      path: '/session'
      fullPath: '/session'
      preLoaderRoute: typeof SessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent-turn': {
      id: '/api/agent-turn'
      path: '/api/agent-turn'
      fullPath: '/api/agent-turn'
      preLoaderRoute: typeof ApiAgentTurnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/illustrate': {
      id: '/api/illustrate'
      path: '/api/illustrate'
      fullPath: '/api/illustrate'
      preLoaderRoute: typeof ApiIllustrateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/research': {
      id: '/api/research'
      path: '/api/research'
      fullPath: '/api/research'
      preLoaderRoute: typeof ApiResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/skills': {
      id: '/api/skills'
      path: '/api/skills'
      fullPath: '/api/skills'
      preLoaderRoute: typeof ApiSkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DevHarnessRoute: DevHarnessRoute,
  DevMermaidHarnessRoute: DevMermaidHarnessRoute,
  SessionRoute: SessionRoute,
  ApiAgentTurnRoute: ApiAgentTurnRoute,
  ApiIllustrateRoute: ApiIllustrateRoute,
  ApiResearchRoute: ApiResearchRoute,
  ApiSkillsRoute: ApiSkillsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
